SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY price) AS p25,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY price) AS p50,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY price) AS p75
FROM STAGING_DB.CLEANED.SILVER_REAL_ESTATE
WHERE price > 0 AND data_quality_score >= {min_quality_score}
