-- Cleanup all databases, tables, and data
-- WARNING: This will permanently delete all data!

-- Drop views first (they depend on tables)
DROP VIEW IF EXISTS ANALYTICS_DB.REPORTING.ACTIVE_ANOMALIES;
DROP VIEW IF EXISTS ANALYTICS_DB.REPORTING.PRICE_TRENDS;
DROP VIEW IF EXISTS ANALYTICS_DB.REPORTING.MARKET_SUMMARY;
DROP VIEW IF EXISTS ANALYTICS_DB.REPORTING.PROPERTY_LISTINGS;

-- Drop ML tables
DROP TABLE IF EXISTS ANALYTICS_DB.ML_RESULTS.FEATURE_IMPORTANCE;
DROP TABLE IF EXISTS ANALYTICS_DB.ML_RESULTS.MODEL_REGISTRY;
DROP TABLE IF EXISTS ANALYTICS_DB.ML_RESULTS.ANOMALY_ALERTS;
DROP TABLE IF EXISTS ANALYTICS_DB.ML_RESULTS.PRICE_PREDICTIONS;

-- Drop Gold tables
DROP TABLE IF EXISTS ANALYTICS_DB.DWH.GOLD_PRICE_TRENDS;
DROP TABLE IF EXISTS ANALYTICS_DB.DWH.GOLD_MARKET_ANALYTICS;
DROP TABLE IF EXISTS ANALYTICS_DB.DWH.GOLD_ML_FEATURES;

-- Drop Silver table
DROP TABLE IF EXISTS STAGING_DB.CLEANED.SILVER_REAL_ESTATE;

-- Drop Bronze table
DROP TABLE IF EXISTS RAW_DB.LANDING.BRONZE_REAL_ESTATE;

-- Drop schemas
DROP SCHEMA IF EXISTS ANALYTICS_DB.REPORTING;
DROP SCHEMA IF EXISTS ANALYTICS_DB.ML_RESULTS;
DROP SCHEMA IF EXISTS ANALYTICS_DB.DWH;
DROP SCHEMA IF EXISTS STAGING_DB.CLEANED;
DROP SCHEMA IF EXISTS RAW_DB.LANDING;

-- Drop databases
DROP DATABASE IF EXISTS ANALYTICS_DB;
DROP DATABASE IF EXISTS STAGING_DB;
DROP DATABASE IF EXISTS RAW_DB;
